# Generated by Django 3.2.23 on 2024-03-13 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Segment', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Classify',
        ),
        migrations.DeleteModel(
            name='FileConvert',
        ),
        migrations.RenameField(
            model_name='segment',
            old_name='img',
            new_name='File',
        ),
        migrations.RenameField(
            model_name='segment',
            old_name='fileName',
            new_name='FileName',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='fileType',
        ),
    ]
